// 0x0E000734
const GeoLayout ssl_geo_000734[] = {
    GEO_CULLING_RADIUS(700),
    GEO_OPEN_NODE(),
#ifdef DECEMBER
      GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 0xB4, 550),
#else
      GEO_SHADOW(SHADOW_SQUARE_SCALABLE, 0xB4, 550),
#endif
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_OPAQUE, ssl_seg7_dl_070220A8),
            GEO_DISPLAY_LIST(LAYER_ALPHA, ssl_seg7_dl_070221E8),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};
