const GeoLayout rr_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND(BACKGROUND_BELOW_CLOUDS, geo_skybox_main),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, 0, 0, 0, -100, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -1573, 2133, 3683, rr_dl_CruiseShip_dl_mesh_layer_1),
					GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -1573, 2133, 3683, rr_dl_CruiseShip_dl_001_mesh_layer_1),
					GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 0, 4749, -3682, rr_dl_FireHouse_dl_mesh_layer_1),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, rr_dl_flamethrowers_dl_mesh_layer_1),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, rr_dl_pebble_platforms_dl_mesh_layer_1),
					GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 3950, 830, 547, rr_dl_pole_dl_mesh_layer_1),
					GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 2940, 2118, 1941, rr_dl_pole_dl_001_mesh_layer_1_with_revert),
					GEO_DISPLAY_LIST(LAYER_TRANSPARENT, rr_dl_rainbow_path_dl_mesh_layer_5_with_revert),
					GEO_RENDER_OBJ(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_ASM(0, geo_cannon_circle_base),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
